language: php

php:
  - '7.1'
  - '7.2'

before_script:
    - curl -sSfL -o ./phpunit https://phar.phpunit.de/phpunit-5.7.phar
    - travis_retry composer install

script: php ./phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
